### ISSUE TITLE
Possible replacement

### ISSUE THREAD

**Issue by Voultapher** [pauldreik/cppsandbox#1]
Nice work! Just some of my thought after taking a quick look.

`std::hardware_concurrency` is useful to be target agnostic  
`std::async(task)` should most likely be `std::async(std::launch::async, task)`

With C++17 you could just use [inclusive_scan](http://en.cppreference.com/w/cpp/algorithm/inclusive_scan)
E.g: `std::inclusive_scan(std::execution::par_unseq, std::begin(in), std::end(in), std::begin(out));` which has the benefit of instruction reordering and less overhead due to the lack of exception handling inside the parallel algorithm.

**Comment by pauldreik** [comment]
Thanks for the input!
You are right, I forgot the extra argument to async. Fixed and committed. Will rerun the benchmark later.
Interesting with the c++17 additions, will try to make a c++17 variant and see how it performs. That will be very interesting.
